### ISSUE TITLE
Cargo.lock is outdated

### ISSUE THREAD

**Issue by dmvinson** [starlite-api/fast-query-parsers#10]
Hi, when trying to package starlite with nix I ran into issues building this dependency. The `cargo metadata` command as part of the maturin build process fails because `--frozen` is passed, but the lock file is outdated. A fresh clone of this repo and `cargo metadata` updates the lock file too:
```
diff --git a/Cargo.lock b/Cargo.lock
index 633867c..318953f 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -31,7 +31,7 @@ checksum = "baf1de4339761588bc0619e3cbc0120ee582ebb74b53b4efbf79117bd2da40fd"

 [[package]]
 name = "fast_query_parsers"
-version = "0.2.0"
+version = "0.3.0"
 dependencies = [
  "lazy_static",
  "pyo3",
```
Could a new version of the lockfile be merged in order to fix this issue? For now I'm manually patching it during builds.

**Comment by Goldziher** [comment]
thats peculiarI pushed an update to main, I ran `cargo update` and `poetry update`, so lock files are on the latest version. Lemme know if the problem persists or close the issue otherwise.

**Comment by dmvinson** [comment]
Thanks for the quick response! Sorry my PR didn't fix it.
